apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-challenge
  namespace: sre-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sre-challenge
  template:
    metadata:
      labels:
        app: sre-challenge
    spec:
      containers:
        - name: sre-challenge
          image: localhost/sre-challenge:local
          ports:
            - containerPort: 5000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sre-challenge-secret
                  key: SECRET_KEY
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: sre-challenge-svc
  namespace: sre-challenge
spec:
  selector:
    app: sre-challenge
  type: NodePort
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
